<a href="https://colab.research.google.com/github/Angela-Shanine/NUMERICAL-METHODS/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Matrix and its operation


In [1]:
import numpy as np

### Shapes

In [21]:
A= np.array ([2 , -1 ,3,
       1, 0, -1 ])
A.shape

(6,)

In [27]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [38]:
C = np.array([
    [1,2,3,4],
    [1,0,2,1],
    [1,6,7,5]
])
C.shape

(3, 4)

### Addition

In [10]:
A= np.array ([2 , -1 ,3,
       1, 0, -1 ])
B = np.array([0 ,0,0, 
     0 , 0 ,0])

A + B # The sum of the two array (A and B)

array([ 2, -1,  3,  1,  0, -1])

In [16]:
A= np.array ([4 , -1,
       6, -3 ])
B = np.array([-6 , -5, 
     7 ,3])

A + B

array([-2, -6, 13,  0])

### Subtraction


In [14]:
A= np.array ([1 , 2,
              -2 , 0,
               -3, -1 ])
B = np.array([1, -1 ,
              1, 3,
               2,3])

A-B

array([ 0,  3, -3, -3, -5, -4])

In [17]:
A= np.array ([4 , -1,
       6, -3 ])
B = np.array([-6 , -5, 
     7 ,3])

A - B

array([10,  4, -1, -6])

### Transpose

In [20]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

### EYE


In [36]:
e=np.eye (2)
e

array([[1., 0.],
       [0., 1.]])

In [37]:
e=np.eye (8)
e

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

### Dot Product

In [29]:
A = np.array([
    [1,2],
    [0,1]
])
B = np.array([
    [-1,0],
    [2,2]
])
np.dot(A,B)

array([[3, 4],
       [2, 2]])

### Diagonal

In [39]:
e = np.diagonal([
    [1,2,3],
    [1,0,2],
    [1,6,7]
])
e

array([1, 0, 7])

In [40]:
A = np.diagonal([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
A

array([1, 5, 9])

### Empty

In [48]:
A = np.empty([0,4])
A

array([], shape=(0, 4), dtype=float64)

In [49]:
A = np.empty([0,0,3])
A

array([], shape=(0, 0, 3), dtype=float64)

### Zeroes

In [50]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])